---
title: "Gov 50 Final Project"
author: "Victor Flores"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to...

```{r}
library(tidyverse)
cfst_data <-  read.csv("Data/download_matrix complete.csv")

```

```{r}
cfst_data$country <- c("Algeria", "Andorra", "Argentina", "Armenia", "Australia", "Azerbaijan", "Bahrain", "Belarus", "Brazil", "Bulgaria", "Burkina Faso", "Canada", "Chile", "China", "Colombia", "Cyprus", "Ecuador", "Egypt", "Estonia", "Ethiopia", "Finland", "France", "Georgia", "Germany", "Ghana", "Great Britain", "Guatemala", "Hong Kong", "Hungary", "India", "Indonesia", "Iran", "Iraq", "Italy", "Japan", "Jordan", "Kazakhstan", "Kuwait", "Kyrgyzstan", "Lebanon", "Libya", "Malaysia", "Mali", "Mexico", "Moldova", "Morocco", "Netherlands", "New Zealand", "Nigeria", "Norway", "Pakistan", "Palestine", "Peru", "Philippines", "Poland", "Qatar", "Romania", "Russia", "Rwanda", "Serbia and Montenegro", "Singapore", "Slovenia", "South Africa", "South Korea", "Spain", "Sweden", "Switzerland", "Taiwan", "Thailand", "Trinidad and Tobago", "Tunisia", "Turkey", "Ukraine", "United States", "Uruguay", "Uzbekistan", "Viet Nam", "Yemen", "Zambia", "Zimbabwe")

```

```{r}
us_data <- cfst_data |>
  select("country", "United.States2005.2014"
  )
us_cfst_plot <- us_data |>
  slice_min(United.States2005.2014, n = 79) |>
  mutate(country = fct_reorder(country, United.States2005.2014)) |>
  ggplot(aes(
    x = United.States2005.2014,
    y = country)) +
  geom_bar(stat = "identity") +
  labs(
    x = "CFst Score",
    y = "Country",
    title = "Country CFst Scores in Relation to the United States",
    caption = "Data provided by Muthukrishna et al."
  ) +
  theme_minimal()

us_cfst_plot
```

```{r}
library(dplyr)
democratic_countries <- cfst_data|>
 filter(country %in% c("Australia", "New Zealand", "Uruguay", "Great Britain", "Finland", "Norway", "Austria", "Canada", "Germany", "Switzerland", "United States", "Hungary", "Netherlands", "Spain", "Sweden", "Japan", "Cyprus", "Bulgaria", "Estonia", "France", "Italy", "Poland", "Romania", "Slovenia"))
democratic_countries$rights_type <- c(0, 2, 1, 2, 2, 4, 2, 1, 3, 4, 2, 0, 2, 5, 4, 2, 2, 2, 4, 4, 1, 1, 5)
rights_type_tibble <- democratic_countries |>
  select("country", "rights_type")
rights_type_tibble
```

